## Acceptance platform pipeline. 

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
 pipelines:
   - pipeline: gluupassport
     source: sign-in-canada.gluu-passport
   - pipeline: shiboxauthauthn3
     source: sign-in-canada.shib-oxauth-authn3

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  major_minor: '1.0'
  # define b as a counter with the prefix as variable a, and seed as 10.
  build: $[counter(variables['major_minor'], 0)]

steps:

- script: |
    ls -al $(Pipeline.Workspace)
    cd gluu-server/opt/gluu/jetty/oxauth/custom
    tar -czv --owner=root --group=root -f custom.tgz *
    mv custom.tgz $(Pipeline.Workspace)/s/gluu-server/opt/dist/signincanada
    cd $(Pipeline.Workspace)
    ls -al s/gluu-server/opt/dist/signincanada
    tar -tvf s/gluu-server/opt/dist/signincanada/custom.tgz
  displayName: 'Packaging UI'
  continueOnError: false

- script: |
    echo 'Downloading AppInsights SDK'
    wget https://github.com/microsoft/ApplicationInsights-Java/releases/download/2.6.2/applicationinsights-core-2.6.2.jar \
       -P gluu-server/opt/dist/signincanada
    echo 'Downloading AppInsights Agent'
    wget https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.0.2/applicationinsights-agent-3.0.2.jar \
       -P gluu-server/opt/azure
    ls -al 
  displayName: 'Downloading AppInsights'
  continueOnError: false

- script: |
    wget https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz \
      -P gluu-server/opt/dist/app
    wget  https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz.sig \
      -P $(Agent.TempDirectory)
    echo 'Checking file integritiy'
    gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys B04F24E3
    gpg2 --verify $(Agent.TempDirectory)/amazon-corretto-11-x64-linux-jdk.tar.gz.sig gluu-server/opt/dist/app/amazon-corretto-11-x64-linux-jdk.tar.gz
  displayName: 'Downloading Latest Amazon Corretto'
  continueOnError: false

- script: |
    wget https://repo1.maven.org/maven2/com/couchbase/client/core-io/1.7.19/core-io-1.7.19.jar \
      -P gluu-server/opt/dist/app
    wget https://repo1.maven.org/maven2/com/couchbase/client/core-io/1.7.19/core-io-1.7.19.jar.asc \
      -P $(Agent.TempDirectory)
      wget https://repo1.maven.org/maven2/com/couchbase/client/java-client/2.7.19/java-client-2.7.19.jar \
      -P gluu-server/opt/dist/app
    wget https://repo1.maven.org/maven2/com/couchbase/client/java-client/2.7.19/java-client-2.7.19.jar.asc \
      -P $(Agent.TempDirectory)
    echo 'Checking download integrity'
    gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys D65B0D0F
    gpg2 --verify $(Agent.TempDirectory)/core-io-1.7.19.jar.asc gluu-server/opt/dist/app/core-io-1.7.19.jar
    gpg2 --verify $(Agent.TempDirectory)/java-client-2.7.19.jar.asc gluu-server/opt/dist/app/java-client-2.7.19.jar
    echo 'Passed'
  displayName: 'Downlaoding the latest Couchbase client'
  continueOnError: false

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7302639f-e704-47c3-9557-99b4e04a75bc'
    definition: '285'
    buildVersionToDownload: 'latest'
    artifactName: 'gluu-passport'
    targetPath: '$(Pipeline.Workspace)/s/gluu-server/opt/dist/gluu'
  displayName: 'Download gluu-passport tarballs'
  continueOnError: false

- script: |
    cd gluu-server/opt/dist/gluu
    mv passport-version_4.1.0-node_modules.tar.gz passport-version_4.2.3-node_modules.tar.gz
  displayName: 'Renaming node modules'
  continueOnError: true

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7302639f-e704-47c3-9557-99b4e04a75bc'
    pipeline: '288'
    runVersion: 'latestFromBranch'
    runBranch: "refs/heads/version_4.2.3"
    artifactName: 'shib-oxauth-authn3'
    targetPath: '$(Pipeline.Workspace)/s/gluu-server/opt/dist/signincanada'
  displayName: 'Downloading shib-oxauth-authn3 libs'

- script: |
    cd gluu-server/opt/dist/signincanada
    mkdir shibjar && tar -C shibjar -xvf shib-oxauth-authn3-4.2.3.sic1.tar
    cp shibjar/shib-oxauth-authn3-4.2.3.sic1/edit-webapp/WEB-INF/lib/shib-oxauth-authn3-4.2.3.sic1.jar .
    rm -rf shib-oxauth-authn3-4.2.3.sic1.tar && rm -rf shib-oxauth-authn3-4.2.3.sic1.zip && rm -rf shibjar
    ls -al 
  displayName: 'Moving Shiboleth Jar'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7302639f-e704-47c3-9557-99b4e04a75bc'
    pipeline: '351'
    buildVersionToDownload: 'latest'
    artifactName: 'node-services'
    targetPath: '$(Pipeline.Workspace)/s/gluu-server/opt/dist/signincanada'
  displayName: 'Downloading node-services tarball'

- script: |
    pushd gluu-server/
    echo 'packaging tarball'
    mkdir -p install/community-edition-setup/static/extension
    tar xvzf opt/dist/signincanada/custom.tgz --strip-components=1 -C install/community-edition-setup/static/extension scripts
    chmod 755 $(find . -type d -print)
    chmod 644 $(find . -type f -print)
    chmod 700 opt/dist/signincanada/postinstall.sh
    chmod 700 opt/dist/scripts/azure/keyvault.sh
    chmod 755 opt/dist/scripts/notify
    chmod 700 opt/dist/scripts/crlcheck.sh
    chmod 700 install/community-edition-setup/setup.py
    tar -czv --owner=root --group=root -f $(Build.ArtifactStagingDirectory)/SIC-AP-1.0.$(build).tgz --exclude='opt/gluu' *
    openssl sha256 $(Build.ArtifactStagingDirectory)/SIC-AP-1.0.$(build).tgz > $(Build.ArtifactStagingDirectory)/SIC-AP-1.0.$(build).tgz.sha
    popd
  displayName: 'Packaging tarball'
  continueOnError: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'acceptance-platform'
    publishLocation: 'pipeline'