## Acceptance platform pipeline. 

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  - develop
variables:
  major_minor: '1.4'
  # define b as a counter with the prefix as variable a, and seed as 10.
  build: $[counter(variables['major_minor'], 0)]

stages:
- stage: Build
  displayName: "Package and publish the Acceptance Platform tarball"
  jobs:
  - job: Package
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/pipeline-utils/azure-sdk/pom.xml'
        goals: 'package'
      displayName: 'Downloading Azure Java SDK libraries'
      continueOnError: false

    - script: |
        ls -al $(Pipeline.Workspace)
        cd gluu-server/opt/gluu/jetty/oxauth/custom
        mkdir libs
        cp -R $(Build.SourcesDirectory)/pipeline-utils/azure-sdk/target/dependency/*.jar libs
        tar -czv --owner=root --group=root -f custom.tgz *
        mv custom.tgz $(Pipeline.Workspace)/s/gluu-server/opt/dist/signincanada
        cd $(Pipeline.Workspace)
        ls -al s/gluu-server/opt/dist/signincanada
        tar -tvf s/gluu-server/opt/dist/signincanada/custom.tgz
      displayName: 'Packaging oxAuth custom UI and libraries'
      continueOnError: false

    - script: |
        echo 'Downloading AppInsights Agent'
        wget https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.4.8/applicationinsights-agent-3.4.8.jar \
          -P gluu-server/opt/azure
        ls -al 
      displayName: 'Downloading AppInsights'
      continueOnError: false

    - script: |
        wget https://sicpub.blob.core.windows.net/software/fido2-patch.war \
          -P gluu-server/opt/dist/signincanada
      displayName: 'Downloading SIC FIDO2 patch'
      continueOnError: false

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '7302639f-e704-47c3-9557-99b4e04a75bc'
        definition: '285'
        runVersion: 'latestFromBranch'
        runBranch: "refs/heads/sic/develop"
        artifactName: 'gluu-passport'
        targetPath: '$(Pipeline.Workspace)/s/gluu-server/opt/dist/gluu'
      displayName: 'Download gluu-passport tarballs'
      continueOnError: false

    - script: |
        cd gluu-server/opt/dist/gluu
        mv passport-version_5.3.0-node_modules.tar.gz passport-version_4.4.0-node_modules.tar.gz
      displayName: 'Renaming node modules'
      continueOnError: true

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '7302639f-e704-47c3-9557-99b4e04a75bc'
        pipeline: '351'
        buildVersionToDownload: 'latest'
        artifactName: 'node-services'
        targetPath: '$(Pipeline.Workspace)/s/gluu-server/opt/dist/signincanada'
      displayName: 'Downloading node-services tarball'

    - script: |
        pushd gluu-server/
        echo 'packaging tarball'
        mkdir -p install/community-edition-setup/static/extension
        tar xvzf opt/dist/signincanada/custom.tgz --strip-components=1 --exclude scripts/person_authentication/sic -C install/community-edition-setup/static/extension scripts
        chmod 755 $(find . -type d -print)
        chmod 644 $(find . -type f -print)
        chmod 700 opt/dist/signincanada/postinstall.sh
        chmod 700 opt/dist/scripts/azure/keyvault.sh
        chmod 755 opt/dist/scripts/notify
        chmod 700 opt/dist/scripts/crlcheck.sh
        chmod 700 opt/dist/scripts/cbcheck.sh
        chmod 700 opt/dist/scripts/passportkeys.sh
        chmod 700 install/community-edition-setup/setup.py
        tar -czv --owner=root --group=root -f $(Build.ArtifactStagingDirectory)/SIC-AP-$(major_minor).$(build).tgz --exclude='opt/gluu' *
        openssl sha256 $(Build.ArtifactStagingDirectory)/SIC-AP-$(major_minor).$(build).tgz > $(Build.ArtifactStagingDirectory)/SIC-AP-$(major_minor).$(build).tgz.sha
        popd
      displayName: 'Packaging tarball'
      continueOnError: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifact: 'acceptance-platform'
        publishLocation: 'pipeline'

  - job: Publish
    pool:
      vmImage: 'windows-latest'
    dependsOn: Package

    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        artifact: 'acceptance-platform'
        path: $(Build.ArtifactStagingDirectory)

    - task: AzureFileCopy@4
      inputs:
        sourcePath: $(Build.ArtifactStagingDirectory)\*
        azureSubscription: 'SIC Service Connection'
        destination: azureBlob
        storage: sicpub
        containerName: staging

- stage: QA
  displayName: "Quality Assurance Testing"
  condition: and(succeeded('Build'), or(eq(variables['Build.Reason'], 'PullRequest'), and(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))))
  jobs:
  - deployment: Deploy
    displayName: Deploy to the QA Environment
    environment: QA
    pool: server
    timeoutInMinutes: 4320
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualValidation@0
            timeoutInMinutes: 4320 # task times out in 3 days
            inputs:
              notifyUsers: 'SignIn-AuthentiCanada@tbs-sct.gc.ca'
              instructions: 'Please install SIC-AP-$(major_minor).$(build) to QA'
              onTimeout: 'reject'

- stage: CATE
  displayName: "Client Acceptance Testing"
  condition: and(succeeded('QA'), or(eq(variables['Build.Reason'], 'PullRequest'), and(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))))
  jobs:
  - deployment: Deploy
    displayName: Deploy to CATE
    environment: CATE
    pool: server
    timeoutInMinutes: 4320
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualValidation@0
            timeoutInMinutes: 4320 # task times out in 3 days
            inputs:
              notifyUsers: 'SignIn-AuthentiCanada@tbs-sct.gc.ca'
              instructions: 'Please install SIC-AP-$(major_minor).$(build) to CATE'
              onTimeout: 'reject'

- stage: PROD
  displayName: "Production"
  condition: and(succeeded('CATE'), or(eq(variables['Build.Reason'], 'PullRequest'), and(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))))
  jobs:
  - deployment: Deploy
    displayName: Deploy to the production environment
    environment: PROD
    pool: server
    timeoutInMinutes: 4320
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualValidation@0
            timeoutInMinutes: 4320 # task times out in 3 days
            inputs:
              notifyUsers: 'SignIn-AuthentiCanada@tbs-sct.gc.ca'
              instructions: 'Please install SIC-AP-$(major_minor).$(build) to PROD'
              onTimeout: 'reject'
